[project]
name = "nashdom-sync"
version = "0.1.0"
description = "Синхронизация данных NashDom с Integration Platform"
readme = "README.md"
authors = [
    { name = "EHoTuK1", email = "mhernov13102@gmail.com" }
]
requires-python = ">=3.8,<3.9"
dependencies = [
    "pydantic==1.10.26",
    "runtime-files",
    "selenium==4.27.1",
    "tomli>=2.4.1",
]

[build-system]
requires = ["uv_build>=0.12.3,<0.13.0"]
build-backend = "uv_build"

[tool.uv.sources]
runtime-files = { workspace = true }
