[logging]
level = "DEBUG"
console = true
log_payloads = false
max_bytes = 50000000
backup_count = 4

[browser]
headless = false   # Переключение отображения браузера

[bitrix]
gateway_url = "http://127.0.0.1:8765"
timeout = 180.0

[extract.nashdom]
objects_to_parse_count = 35   # Кол-во объектов КАЖДОГО РЕГИОНА для парсинга